version: '3.1'

services:

  hotdesk-service:
    image: localhost:5000/hotdesk-service
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
        - db

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
